staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/3.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 21724
# - Commit ID: 0e632f0f3d55054342febd060632777ef4bd6958
# - Timestamp: 2024-10-16T12:03:17Z
