staging:
  profile: ~
  whoami: 2.x-site-stg-out
  subdir: content/log4j/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 10120
# - Commit ID: 96f5fe7b8ea49c4b6a3249d4cade5d09a218812d
# - Timestamp: 2024-09-12T15:13:58Z
