staging:
  profile: ~
  whoami: 2.x-site-stg-out
  subdir: content/log4j/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 23690
# - Commit ID: b55c4d3fa2489cf91d6569aac57b05ae2c9d4b06
# - Timestamp: 2024-10-01T20:05:54Z
