staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/3.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 29596
# - Commit ID: c627e52995a69a812a6400988063d2dede54f2f7
# - Timestamp: 2024-10-09T12:17:22Z
