staging:
  profile: ~
  whoami: 2.x-site-stg-out
  subdir: content/log4j/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 13890
# - Commit ID: 08778fb0a33b1aa02079545ebddb6d37cd10022b
# - Timestamp: 2024-09-18T10:34:22Z
