staging:
  profile: ~
  whoami: 2.x-site-stg-out
  subdir: content/log4j/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 26416
# - Commit ID: f1d1d3a41089b0971bb611058c4e01a40e6d290f
# - Timestamp: 2024-11-02T13:36:40Z
